package org.dimas.finance.ar;

import javax.persistence.Id;

import com.vaadin.annotations.AutoGenerated;

public class ArSummarySalesCustModel {
	@Id
	@AutoGenerated
	private long id;
	private String kode;
	private String ket;
	private String ket2;
	private double cashAmount;
	private double returAmount;
	private double giroAmount;
	private double transferAmount;
	private double potAmount;
	private double totalAmount;
	public long getId() {
		return id;
	}
	public void setId(long id) {
		this.id = id;
	}
	public String getKode() {
		return kode;
	}
	public void setKode(String kode) {
		this.kode = kode;
	}
	public String getKet() {
		return ket;
	}
	public void setKet(String ket) {
		this.ket = ket;
	}
	public double getCashAmount() {
		return cashAmount;
	}
	public void setCashAmount(double cashAmount) {
		this.cashAmount = cashAmount;
	}
	public double getReturAmount() {
		return returAmount;
	}
	public void setReturAmount(double returAmount) {
		this.returAmount = returAmount;
	}
	public double getGiroAmount() {
		return giroAmount;
	}
	public void setGiroAmount(double giroAmount) {
		this.giroAmount = giroAmount;
	}
	public double getTransferAmount() {
		return transferAmount;
	}
	public void setTransferAmount(double transferAmount) {
		this.transferAmount = transferAmount;
	}
	public double getPotAmount() {
		return potAmount;
	}
	public void setPotAmount(double potAmount) {
		this.potAmount = potAmount;
	}
	public double getTotalAmount() {
		return totalAmount;
	}
	public void setTotalAmount(double totalAmount) {
		this.totalAmount = totalAmount;
	}
	public String getKet2() {
		return ket2;
	}
	public void setKet2(String ket2) {
		this.ket2 = ket2;
	}
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + (int) (id ^ (id >>> 32));
		return result;
	}
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ArSummarySalesCustModel other = (ArSummarySalesCustModel) obj;
		if (id != other.id)
			return false;
		return true;
	}
	@Override
	public String toString() {
		return id + "- " + kode;
	}
	
	
}
